### ISSUE TITLE
[Design] 需要几个常规页面设计

### ISSUE THREAD

**Issue by frank-zsy** [wuhan2020/wuhan2020-frontend-react-app#2]
目前网站已经可运行，我们需要几个常规页面的设计

* 404.html：当访问错误网址，找不到内容时显示的
* 500.html：当服务器出现错误时显示的

这两个页面的内容可由设计师自由发挥，需要文案内容请联系官网组，提 Issue 到 https://github.com/wuhan2020/wuhan2020.github.io

**Comment by oozliuoo** [comment]
已经提交了设计，关闭此 issue。
