### ISSUE TITLE
【需求】完成捐款页面的开发

### ISSUE THREAD

**Issue by oozliuoo** [wuhan2020/wuhan2020-frontend-react-app#4]
[设计稿](https://www.figma.com/file/6oLZ4Swo2He0w8DUNELsUV/wuhan?node-id=1308%3A3644)

**Comment by katejia110** [comment]
设计稿： 
https://www.figma.com/file/Dq4SyxvTwO7lDQVnwox36G/wuhan-v1-rapid-prototype?node-id=1308%3A3645 
这个部分的数据表格有整理
只捐款。后端请和 Frank 对接好。

**Comment by oozliuoo** [comment]
捐款的数据结构

```json
{
	"id": 0,
	"name": "华中科技大学北京校友会",
	"contacts": [],
	"address": null,
	"email": null,
	"wechat": null,
	"bankAccounts": [{
		"name": "宋扬",
		"bank": "中国民生银行北京工体北路支行",
		"number": "6216 9101 0452 6790"
	}],
	"rfb": null,
	"remark": "此账户为北京校友会机动账户",
	"date": null,
	"url": "https://mp.weixin.qq.com/s/dXed5MIYgBisrV_pfQmV0w",
	"status": "进行中"
}
```

**Comment by oozliuoo** [comment]
Remaining TODOs as mentioned in [PR#11](https://github.com/wuhan2020/wuhan2020-frontend-react-app/pull/11):

Pagination
Filter by having wechat/alipay or not
Filter by location (no location data yet)
