### ISSUE TITLE
[Bug]Tab 同时高亮 

### ISSUE THREAD

**Issue by reetaxu** [wuhan2020/wuhan2020-frontend-react-app#41]
Step:
1. 当前页面在 “物流” ’模块
2. 光标移至 “酒店” 模块的tab上
出现两个tab同时高亮的情形，且高亮的线会连在一起

**Comment by damingerdai** [comment]
这个应该不算bug

**Comment by oozliuoo** [comment]
这个是 expected 的，active 和 hover 的样式是同样的，因此会同时显示
