### ISSUE TITLE
【需求】完成义诊页面的开发

### ISSUE THREAD

**Issue by oozliuoo** [wuhan2020/wuhan2020-frontend-react-app#5]
[设计稿](https://www.figma.com/file/6oLZ4Swo2He0w8DUNELsUV/wuhan?node-id=29%3A0) - 第一版（无标签超级简化版）

**Comment by katejia110** [comment]
设计link： 
https://www.figma.com/file/Dq4SyxvTwO7lDQVnwox36G/wuhan-v1-rapid-prototype?node-id=1759%3A5824  
第一版先做pagination
第二版改进infinitely scrolling （后端ready 以后）
