### ISSUE TITLE
【需求】完成指定接待酒店的开发

### ISSUE THREAD

**Issue by oozliuoo** [wuhan2020/wuhan2020-frontend-react-app#6]

**Comment by yaluye** [comment]
设计稿：https://www.figma.com/file/Dq4SyxvTwO7lDQVnwox36G/wuhan-v1-rapid-prototype?node-id=46%3A2

”湖北医护人员“和“武汉在外人士”指定酒店作为二级分类(tab) 放在同一个“住宿”页面内。住宿项采用同一个卡片模块。用户可以从其他页面直接跳转到不同tab选项。有些项如果有备注或者其他信息（如可接人员和可提供房间），卡片可展开查看这些信息。

如果其中一个信息表不全暂时不能上线，就去掉tab，直接在页面标题上注明可上线的是什么住宿列表，比如“湖北医务人员住宿”。

“武汉在外人士”那个表格上有些数据也不全，比如有些没有 “联系人(酒店名称或者政府部门）” ，我建议在这种情况下暂时使用市区信息。

另外，”武汉在外人士”这个copy可能不完全准确，需要另外想一想copy，比如 ”在外游客”？

**Comment by oozliuoo** [comment]
本页面已完成第一版的开发，返回的数据中没有 `remark` 的信息（值为空），故没有显示
