### ISSUE TITLE
【需求】接入疫情地图

### ISSUE THREAD

**Issue by oozliuoo** [wuhan2020/wuhan2020-frontend-react-app#7]

**Comment by katejia110** [comment]
设计稿： 
https://www.figma.com/file/Dq4SyxvTwO7lDQVnwox36G/wuhan-v1-rapid-prototype?node-id=1836%3A6810
单开一个疫情的页面
可视化的图由viz 组提供

**Comment by oozliuoo** [comment]
部分内部样式需要 `viz` 调整后拉取更新的组件来完成调整。
